import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
    test
}: Readonly<{
  children: React.ReactNode;
    test: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header>Menu</header>
      {children}
      {test}
      </body>
    </html>
  );
}
